import type {ProductInput} from '../types'

// source: retailer fitment listings (e.g. https://finditparts.com) matched by part number; entries without a fitment line could not be verified.
export const products: ProductInput[] = [
  {
    title: 'Engine Air Filter AF 12061',
    sku: 'AF 12061',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number AF 12061. Retail listings show fitment for Honda Odyssey (2018-2022), Pilot (2016-2022), Ridgeline (2017-2022) and Passport (2019-2022); Acura MDX (2016-2020) and TLX (2021-2023); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter AF 12289',
    sku: 'AF 12289',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number AF 12289. Retail listings show fitment for Toyota Camry (2018-2022), Corolla (2019-2022), RAV4 (2019-2022), Avalon (2019-2022), Highlander (2020-2022), C-HR (2018-2022); select Lexus ES and UX; Subaru BRZ; confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10171',
    sku: '10171',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10171. Retail listings show fitment for Toyota Camry (2007-2017) and Venza (2009-2016); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12050',
    sku: '12050',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12050. Retail listings show fitment for Honda CR-V (2017-2022) and Civic (2016-2021) with the 1.5L engine; confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12051',
    sku: '12051',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12051. Retail listings show fitment for Honda Civic (2016-2023); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10889',
    sku: '10889',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10889. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11259',
    sku: '11259',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11259. Retail listings show fitment for Mazda CX-5 (2013-2024), Mazda3 (2012-2018) and Mazda6 (2014-2021); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10344',
    sku: '10344',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10344. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11399',
    sku: '11399',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11399. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11042',
    sku: '11042',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11042. Retail listings show fitment for Honda Odyssey (2011-2017); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10467',
    sku: '10467',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10467. Retail listings show fitment for Honda Accord 2.4L (2008-2012) and Crosstour 2.4L (2012-2015); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12259',
    sku: '12259',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12259. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11053A',
    sku: '11053A',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11053A. Retail listings show fitment for select Hyundai and Kia models including Kia Rondo (2014-2017); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10885',
    sku: '10885',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10885. Retail listings show fitment for Honda CR-V 2.4L (2010-2011); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11945',
    sku: '11945',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11945. Retail listings show fitment for Honda CR-V (2015-2016); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12777',
    sku: '12777',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12777. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10013',
    sku: '10013',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10013. Retail listings show fitment for Honda Pilot (2009-2015), Honda Odyssey (2005-2010) and Acura MDX (2007-2009); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10755',
    sku: '10755',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10755. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11113',
    sku: '11113',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11113. Retail listings show fitment for Honda Civic (2012-2015) and Acura ILX (2013-2015); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11500',
    sku: '11500',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11500. Retail listings show fitment for Hyundai Santa Fe (2013-2018), Santa Fe Sport (2013-2016), Santa Fe XL (2013-2019) and Kia Sorento (2014-2015); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10094',
    sku: '10094',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10094. Retail listings show fitment for Mazda6 (2009-2013), Ford Fusion (2006-2012) and Mercury Milan (2006-2011); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10330',
    sku: '10330',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10330. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10346',
    sku: '10346',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10346. Retail listings show fitment for Nissan Sentra (2007-2012); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10349',
    sku: '10349',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10349. Retail listings show fitment for Nissan Altima 2.5L (2007-2013); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10359',
    sku: '10359',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10359. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10468',
    sku: '10468',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10468. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10470',
    sku: '10470',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10470. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10616',
    sku: '10616',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10616. Retail listings show fitment for Ford Escape (2009-2012), Mercury Mariner (2009-2011) and Mazda Tribute (2009-2011); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10677',
    sku: '10677',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10677. Retail listings show fitment for Toyota RAV4 (2013-2018), Avalon (2013-2018) and Camry (2012-2017); Lexus ES300h (2013-2018) and LS460 (2007-2017); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11090',
    sku: '11090',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11090. Confirm the application against your vehicle or the original filter before ordering. Also listed as 12816.',
  },
  {
    title: 'Engine Air Filter 11256',
    sku: '11256',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11256. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11258',
    sku: '11258',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11258. Retail listings show fitment for Honda CR-V (2012-2014); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11426',
    sku: '11426',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11426. Retail listings show fitment for Toyota Corolla (2020-2025) and Prius (2016-2022); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11858',
    sku: '11858',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11858. Retail listings show fitment for Nissan Qashqai (2017-2022); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12052',
    sku: '12052',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12052. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12057',
    sku: '12057',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12057. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12665',
    sku: '12665',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12665. Confirm the application against your vehicle or the original filter before ordering. Also listed as 12666.',
  },
  {
    title: 'Engine Air Filter 9401',
    sku: '9401',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 9401. Confirm the application against your vehicle or the original filter before ordering. Also listed as 12375.',
  },
  {
    title: 'Engine Air Filter 9898',
    sku: '9898',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 9898. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 9800',
    sku: '9800',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 9800. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12932',
    sku: '12932',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12932. Confirm the application against your vehicle or the original filter before ordering. Also listed as 99892.',
  },
  {
    title: 'Engine Air Filter 12377',
    sku: '12377',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12377. Retail listings show fitment for Toyota Camry (2018-2024), RAV4 (2019-2024), Highlander (2020-2024) and Avalon (2019-2022); select Lexus ES, NX and RX; confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10169',
    sku: '10169',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10169. Retail listings show fitment for Toyota Venza (2009-2016) and Scion tC (2011-2016); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 8755A',
    sku: '8755A',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 8755A. Confirm the application against your vehicle or the original filter before ordering. Also listed as 8756.',
  },
  {
    title: 'Engine Air Filter 12290',
    sku: '12290',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12290. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11948',
    sku: '11948',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11948. Retail listings show fitment for Chrysler 200 (2015-2017); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12297',
    sku: '12297',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12297. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10539',
    sku: '10539',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10539. Retail listings show fitment for Hyundai Santa Fe (2007-2009); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10488',
    sku: '10488',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10488. Retail listings show fitment for Ford Focus (2008-2011); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10262',
    sku: '10262',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10262. Retail listings show fitment for Ford F-Series trucks including F-150 (2009-2022) and Super Duty (2008-2016); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10347',
    sku: '10347',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10347. Retail listings show fitment for Lexus IS250 (2006-2013), IS350 (2006-2015), GS350 (2007-2011) and GS430 (2006-2007); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11257',
    sku: '11257',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11257. Retail listings show fitment for Dodge Charger, Chrysler 300 and Dodge Challenger (2011-2022); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10910',
    sku: '10910',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10910. Retail listings show fitment for Mitsubishi RVR (2013-2022), Outlander Sport (2013-2022), Lancer (2013-2017) and Outlander (2014-2020); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11010',
    sku: '11010',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11010. Retail listings show fitment for Acura MDX (2010-2013) and ZDX (2010-2013); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10465',
    sku: '10465',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10465. Retail listings show fitment for Chevrolet Equinox and GMC Terrain (2010-2017); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11480',
    sku: '11480',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11480. Retail listings show fitment for Lincoln Nautilus (2019-2023), Continental (2017-2020), MKX (2016-2018) and Ford Edge (2015 onward); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10242',
    sku: '10242',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10242. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11251',
    sku: '11251',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11251. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11050',
    sku: '11050',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11050. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11450',
    sku: '11450',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11450. Retail listings show fitment for Nissan Altima (2013-2018); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12815',
    sku: '12815',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12815. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10578',
    sku: '10578',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10578. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10261',
    sku: '10261',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10261. Retail listings show fitment for Ram 2500 to 5500 heavy-duty trucks (roughly 2007-2022); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10650',
    sku: '10650',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10650. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11943',
    sku: '11943',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11943. Retail listings show fitment for select Hyundai (Santa Fe, Palisade) and Kia (Sorento, Sedona, Telluride) models, roughly 2015-2023; confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10086',
    sku: '10086',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10086. Retail listings show fitment for Kia Sportage (2005-2010) and Hyundai Tucson (2005-2009); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11476',
    sku: '11476',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11476. Retail listings show fitment for Honda Accord 2.4L (2013-2017) and Acura TLX 2.4L (2015-2020); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12378',
    sku: '12378',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12378. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10996',
    sku: '10996',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10996. Retail listings show fitment for Lexus GS350 (2013-2020) and IS350 (2014 onward); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11477',
    sku: '11477',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11477. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12088',
    sku: '12088',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12088. Retail listings show fitment for Mazda CX-3 (2016-2021); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10190',
    sku: '10190',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10190. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11413',
    sku: '11413',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11413. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10835',
    sku: '10835',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10835. Retail listings show fitment for Toyota 4Runner (2010-2024) and FJ Cruiser (2010-2014); Lexus GX460 (2010-2023); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11941',
    sku: '11941',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11941. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11170',
    sku: '11170',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11170. Retail listings show fitment for Dodge Journey (2011-2019), Dodge Avenger (2011-2014) and Chrysler 200 (2011-2014); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 9762',
    sku: '9762',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 9762. Retail listings show fitment for Toyota Highlander (2011-2016), Lexus RX450h (2010-2015), Dodge Durango (2004-2009) and Chrysler Aspen (2007-2009); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11712',
    sku: '11712',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11712. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11942',
    sku: '11942',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11942. Retail listings show fitment for Hyundai Sonata (2015-2019) and Kia Optima (2016-2020); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 4309',
    sku: '4309',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 4309. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11121',
    sku: '11121',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11121. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10085',
    sku: '10085',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10085. Retail listings show fitment for Volkswagen Beetle (2012-2014) and Passat (2012-2015); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 11456',
    sku: '11456',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11456. Retail listings show fitment for Ford Escape (2013-2019) and Transit Connect (2014-2022); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10989',
    sku: '10989',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10989. Confirm the application against your vehicle or the original filter before ordering. Also listed as 10867.',
  },
  {
    title: 'Engine Air Filter 10990',
    sku: '10990',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10990. Retail listings show fitment for Chevrolet Cruze (2011-2016) and Buick Verano (2013-2016); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12065',
    sku: '12065',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12065. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 11114',
    sku: '11114',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 11114. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12551',
    sku: '12551',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12551. Retail listings show fitment for Nissan Altima (2019-2022); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 10802',
    sku: '10802',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10802. Retail listings show fitment for Acura TSX (2009-2014); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 12605',
    sku: '12605',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12605. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10881',
    sku: '10881',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10881. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 7440',
    sku: '7440',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 7440. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 6900',
    sku: '6900',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 6900. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10997',
    sku: '10997',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10997. Retail listings show fitment for Ford Fiesta (2011-2019); confirm against your vehicle before ordering.',
  },
  {
    title: 'Engine Air Filter 8997',
    sku: '8997',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 8997. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 10170',
    sku: '10170',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 10170. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12967',
    sku: '12967',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12967. Confirm the application against your vehicle or the original filter before ordering.',
  },
  {
    title: 'Engine Air Filter 12879',
    sku: '12879',
    category: 'engine-air-filters',
    description: 'Replacement engine air filter, part number 12879. Confirm the application against your vehicle or the original filter before ordering.',
  },
]
