import type {ProductInput} from '../types'

// Unbranded oil filters; fitment is only stated where a retailer listing for the matching number supports it.
// source: https://www.carid.com/fram/extra-guard-spin-on-engine-oil-filter-mpn-ph2870a.html (PH2870A)

export const products: ProductInput[] = [
  {
    title: 'Oil Filter 4610',
    sku: '4610',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4610. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 4459',
    sku: '4459',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4459. Also listed as 9688. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 241',
    sku: '241',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 241. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 4477',
    sku: '4477',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4477. Also listed as 4476. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5608 V',
    sku: '5608 V',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5608 V. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 6311',
    sku: '6311',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 6311. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 4612',
    sku: '4612',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4612. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 2222',
    sku: '2222',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 2222. Also listed as 11642. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 4651',
    sku: '4651',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4651. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 10855',
    sku: '10855',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 10855. Also listed as 6127. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5702',
    sku: '5702',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5702. Also listed as 10295. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 11830',
    sku: '11830',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 11830. Also listed as 10473. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5839',
    sku: '5839',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5839. Also listed as 10246. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8161',
    sku: '8161',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Oil filter, part number 8161. Also listed as 10260. Retail listings for the matching number show select Audi and Volkswagen models. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5436',
    sku: '5436',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5436. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 111',
    sku: '111',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 111. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8209',
    sku: '8209',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8209. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 12059',
    sku: '12059',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Cartridge-style oil filter element, part number 12059. Retail listings for the matching number show select recent BMW models. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 2500',
    sku: '2500',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 2500. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5895',
    sku: '5895',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Spin-on oil filter, part number 5895. Also listed as 35895. Retail listings for the matching numbers show select 2008-2018 Audi and Volkswagen models with 2.0L engines. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5607',
    sku: '5607',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5607. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5609',
    sku: '5609',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5609. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5646',
    sku: '5646',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5646. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5581',
    sku: '5581',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5581. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5505',
    sku: '5505',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5505. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 1760',
    sku: '1760',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 1760. Also listed as 11913. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 10040-6296',
    sku: '10040-6296',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 10040-6296. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5276',
    sku: '5276',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5276. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5288',
    sku: '5288',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5288. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 1520',
    sku: '1520',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 1520. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 195',
    sku: '195',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 195. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8154',
    sku: '8154',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8154. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8902',
    sku: '8902',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8902. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 1792',
    sku: '1792',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 1792. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 1752',
    sku: '1752',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 1752. Also listed as 11914. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 6135',
    sku: '6135',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 6135. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 6291',
    sku: '6291',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 6291. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8182',
    sku: '8182',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8182. Also listed as 10259. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8179',
    sku: '8179',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8179. Also listed as 11934. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 6293',
    sku: '6293',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 6293. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5598',
    sku: '5598',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5598. Also listed as 10160. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5844',
    sku: '5844',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5844. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 4011',
    sku: '4011',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4011. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 11715-1424',
    sku: '11715-1424',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 11715-1424. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8157',
    sku: '8157',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8157. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5610',
    sku: '5610',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5610. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 10592',
    sku: '10592',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 10592. Also listed as 9177. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 10277',
    sku: '10277',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 10277. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 10232',
    sku: '10232',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 10232. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5313',
    sku: '5313',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5313. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5274',
    sku: '5274',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5274. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5831',
    sku: '5831',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5831. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 1394',
    sku: '1394',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 1394. Also listed as 12364. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5691',
    sku: '5691',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5691. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 8113',
    sku: '8113',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 8113. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 4670',
    sku: '4670',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 4670. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5830',
    sku: '5830',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5830. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 1403',
    sku: '1403',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 1403. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter CH 10259',
    sku: 'CH 10259',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number CH 10259. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter T252',
    sku: 'T252',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Spin-on oil filter, part number T252. Also listed as PH2870A. Retail listings for PH2870A show select Audi, BMW and Volkswagen models. Sold by the case of 40.',
  },
  {
    title: 'Oil Filter 5564',
    sku: '5564',
    category: 'oil-filters',
    attrs: {'pack-size': 'Case of 40'},
    description: 'Replacement oil filter, part number 5564. Sold by the case of 40.',
  },
]
