import type {ProductInput} from '../types'

export const products: ProductInput[] = [
  // source: https://www.mobil.com/en/lubricants/for-personal-vehicles/our-products/products/mobil-1-0w-20 ; https://www.mobil.com/en/lubricants/for-personal-vehicles/our-products/products/mobil-1-5w-30 ; https://www.mobil.com/en/lubricants/for-personal-vehicles/our-products/products/mobil-1-5w-20
  {
    title: 'Mobil 1 Advanced Fuel Economy 0W-20 Full Synthetic Motor Oil - 3 x 4.73 L',
    sku: '125971',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Mobil',
      viscosity: '0W-20',
      'pack-size': '3 x 4.73 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-6A', 'dexos1 Gen 3'],
    },
    description: 'Low-viscosity full synthetic 0W-20 passenger car motor oil from Mobil 1, supplied as a 3-pack of 4.73 L jugs.',
  },
  {
    title: 'Mobil 1 Advanced Full Synthetic 5W-20 Motor Oil - 3 x 4.73 L',
    sku: '125970',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Mobil',
      viscosity: '5W-20',
      'pack-size': '3 x 4.73 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-6A'],
    },
    description: 'Full synthetic 5W-20 passenger car motor oil from Mobil 1, supplied as a 3-pack of 4.73 L jugs.',
  },
  {
    title: 'Mobil 1 Advanced Full Synthetic 5W-30 Motor Oil - 3 x 4.73 L',
    sku: '125969',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Mobil',
      viscosity: '5W-30',
      'pack-size': '3 x 4.73 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-6A'],
    },
    description: 'Full synthetic 5W-30 passenger car motor oil from Mobil 1, supplied as a 3-pack of 4.73 L jugs.',
  },
  // source: https://www.mobil.com/en-ca/passenger-vehicle-lube/pds/io-xx-mobil-1-fs-5w-40 ; https://www.mobil.com/en/lubricants/for-personal-vehicles/our-products/products/mobil-1-esp-x2-0w-20
  {
    title: 'Mobil 1 FS European Car Formula 5W-40 Full Synthetic Motor Oil - 6 x 1 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Mobil',
      viscosity: '5W-40',
      'pack-size': '6 x 1 L',
      'oil-type': 'Full Synthetic',
      specification: ['VW 502 00', 'VW 505 00', 'MB 229.3', 'MB 229.5', 'BMW Longlife-01', 'Porsche A40', 'ACEA A3/B4'],
    },
    description: 'Full synthetic 5W-40 motor oil formulated for European-specification gasoline and diesel passenger vehicles. Supplied as a case of six 1 L bottles.',
  },
  {
    title: 'Mobil 1 ESP X2 0W-20 Full Synthetic Motor Oil - 6 x 1 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Mobil',
      viscosity: '0W-20',
      'pack-size': '6 x 1 L',
      'oil-type': 'Full Synthetic',
      specification: ['ACEA C5', 'MB 229.71', 'VW 508 00', 'VW 509 00', 'Porsche C20'],
    },
    description: 'Low-ash full synthetic 0W-20 motor oil for newer European vehicles with emission-control systems. Supplied as a case of six 1 L bottles.',
  },
  // source: https://www.canadiantire.ca/en/pdp/p-0287932p.html ; https://shop.sclubricants.com/rotella-t4-trip-prot-10w30-ck4
  {
    title: 'Shell Rotella T4 Triple Protection 10W-30 Heavy Duty Diesel Engine Oil - Pail 18.9 L',
    category: 'hddo-mineral',
    attrs: {
      brand: 'Shell',
      viscosity: '10W-30',
      'pack-size': 'Pail 18.9 L',
      'oil-type': 'Conventional',
      specification: ['API CK-4', 'API CJ-4', 'API CI-4 PLUS'],
    },
    description: 'Conventional heavy duty diesel engine oil with Shell Triple Protection additive technology, API CK-4 rated. Supplied in an 18.9 L pail.',
  },
  {
    title: 'Shell Rotella T4 Triple Protection 15W-40 Heavy Duty Diesel Engine Oil - Pail 18.9 L',
    category: 'hddo-mineral',
    attrs: {
      brand: 'Shell',
      viscosity: '15W-40',
      'pack-size': 'Pail 18.9 L',
      'oil-type': 'Conventional',
      specification: ['API CK-4', 'API CJ-4', 'API CI-4 PLUS', 'ACEA E9'],
    },
    description: 'Conventional 15W-40 heavy duty diesel engine oil with Shell Triple Protection additive technology, API CK-4 rated. Supplied in an 18.9 L pail.',
  },
  // source: https://www.canadiantire.ca/en/pdp/p-0289067p.html ; https://canadiantire.ca/en/pdp/quaker-state-full-synthetic-5w30-engine-motor-oil-5-l-0289037p.html
  {
    title: 'Quaker State Full Synthetic 0W-20 Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Quaker State',
      viscosity: '0W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-6A'],
    },
    description: 'Full synthetic 0W-20 passenger car motor oil, sold in Canada under the Quaker State Full Synthetic name (formerly Ultimate Durability). Supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Quaker State Full Synthetic 5W-20 Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Quaker State',
      viscosity: '5W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Full synthetic 5W-20 passenger car motor oil, sold in Canada under the Quaker State Full Synthetic name (formerly Ultimate Durability). Supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Quaker State Full Synthetic 5W-30 Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Quaker State',
      viscosity: '5W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-6A', 'dexos1 Gen 2'],
    },
    description: 'Full synthetic 5W-30 passenger car motor oil, sold in Canada under the Quaker State Full Synthetic name (formerly Ultimate Durability). Supplied as a 3-pack of 5 L jugs.',
  },
  // source: https://eurocarslube.com/golden-horse.php
  {
    title: 'Golden Horse 0W-20 Synthetic Technology Motor Oil',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Golden Horse',
      viscosity: '0W-20',
      'oil-type': 'Full Synthetic',
    },
    description: 'Synthetic-technology 0W-20 passenger car motor oil from Golden Horse. Check the label for service approvals.',
  },
  {
    title: 'Golden Horse 5W-20 Synthetic Technology Motor Oil',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Golden Horse',
      viscosity: '5W-20',
      'oil-type': 'Full Synthetic',
    },
    description: 'High performance synthetic-technology 5W-20 passenger car motor oil from Golden Horse. Check the label for service approvals.',
  },
  {
    title: 'Golden Horse 5W-30 Synthetic Technology Motor Oil',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Golden Horse',
      viscosity: '5W-30',
      'oil-type': 'Full Synthetic',
    },
    description: 'Synthetic-technology 5W-30 passenger car motor oil from Golden Horse. Check the label for service approvals.',
  },
  {
    title: 'Golden Horse 5W-40 Synthetic Technology Motor Oil',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Golden Horse',
      viscosity: '5W-40',
      'oil-type': 'Full Synthetic',
    },
    description: 'Synthetic-technology 5W-40 passenger car motor oil from Golden Horse. Check the label for service approvals.',
  },
  {
    title: 'Golden Horse 10W-30 Synthetic Blend Motor Oil',
    category: 'pcmo-semi-synthetic',
    attrs: {
      brand: 'Golden Horse',
      viscosity: '10W-30',
      'oil-type': 'Synthetic Blend',
    },
    description: 'Synthetic-technology 10W-30 passenger car motor oil from Golden Horse. Check the label for service approvals.',
  },
  {
    title: 'Golden Horse 15W-40 Long Life Diesel Engine Oil',
    category: 'hddo-mineral',
    attrs: {
      brand: 'Golden Horse',
      viscosity: '15W-40',
    },
    description: 'Long-life 15W-40 diesel engine oil from Golden Horse. Check the label for service approvals.',
  },
  // source: https://conexdist.ro/en/kross-oils/
  {
    title: 'Kross 15W-40 Diesel Engine Oil - Pail',
    category: 'hddo-mineral',
    attrs: {
      brand: 'Kross',
      viscosity: '15W-40',
    },
    description: '15W-40 diesel engine oil from Kross, supplied in a pail. Check the label for service approvals.',
  },
  // source: https://www.liqui-moly.com/en/ca/top-tec-6600-0w-20-p004918.html ; https://www.liqui-moly.com/en/ca/top-tec-6200-0w-20-p004100.html
  {
    title: 'Liqui Moly Top Tec 6600 0W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['ACEA C5', 'ACEA C6', 'API SQ', 'ILSAC GF-7A', 'BMW Longlife-17 FE+', 'MB 229.71', 'MB 229.72'],
    },
    description: 'Fully synthetic low-friction 0W-20 motor oil for gasoline and diesel engines calling for current-specification oils. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Top Tec 6200 0W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['ACEA C5', 'VW 508 00', 'VW 509 00', 'Porsche C20', 'Ford WSS-M2C956-A1'],
    },
    description: 'Fully synthetic low-friction 0W-20 motor oil with VW Group and Porsche low-viscosity approvals. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly 5W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'German-made Liqui Moly full synthetic 5W-20 passenger car motor oil. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  {
    title: 'Liqui Moly 5W-30 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-30',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'German-made Liqui Moly full synthetic 5W-30 passenger car motor oil. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  {
    title: 'Liqui Moly 5W-40 Diesel Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-40',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Liqui Moly full synthetic 5W-40 motor oil for passenger car diesel engines. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  {
    title: 'Liqui Moly 5W-40 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-40',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'German-made Liqui Moly full synthetic 5W-40 passenger car motor oil. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  // source: https://www.liqui-moly.com/en/ca/special-tec-aa-0w-20-p000311.html ; https://www.liqui-moly.com/en/ca/special-tec-aa-5w-20-p000335.html ; https://www.liqui-moly.com/en/ca/special-tec-aa-5w-30-p000334.html ; https://www.liqui-moly.com/en/ca/special-tec-aa-0w-16-p004846.html
  {
    title: 'Liqui Moly Special Tec AA 0W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7A', 'dexos1 Gen 3', 'Chrysler MS-6395', 'Ford WSS-M2C947-B1'],
    },
    description: 'Fully synthetic low-viscosity motor oil for modern Asian and American gasoline engines, including direct-injection and turbocharged units. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Special Tec AA 5W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7A', 'dexos1 Gen 3', 'Chrysler MS-6395', 'Ford WSS-M2C945-B1'],
    },
    description: 'Fully synthetic low-viscosity motor oil for modern Asian and American gasoline engines, including direct-injection and turbocharged units. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Special Tec AA 5W-30 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-30',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7A', 'dexos1 Gen 3', 'Chrysler MS-6395', 'Ford WSS-M2C946-B1'],
    },
    description: 'Fully synthetic low-viscosity motor oil for modern Asian and American gasoline engines, including direct-injection and turbocharged units. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Special Tec AA 0W-16 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-16',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7B'],
    },
    description: 'Fully synthetic extra-low-viscosity 0W-16 motor oil for modern Asian and American gasoline engines. Supplied as a case of four 5 L jugs.',
  },
  // source: https://www.liqui-moly.com/en/ca/products/molygen.html ; https://www.liqui-moly.com/en/ca/molygen-new-generation-0w-20-p004823.html
  {
    title: 'Liqui Moly Molygen New Generation 0W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7A', 'dexos1 Gen 3', 'Chrysler MS-6395', 'Ford WSS-M2C947-B1'],
    },
    description: 'Fully synthetic low-friction 0W-20 motor oil with Molecular Friction Control technology and a green colour. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Molygen New Generation 5W-20 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-20',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7A', 'dexos1 Gen 3'],
    },
    description: 'Fully synthetic low-friction 5W-20 motor oil with Molecular Friction Control technology and a green colour. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Molygen New Generation 5W-30 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-30',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SQ', 'ILSAC GF-7A', 'dexos1 Gen 3'],
    },
    description: 'Fully synthetic low-friction 5W-30 motor oil with Molecular Friction Control technology and a green colour. Supplied as a case of four 5 L jugs.',
  },
  {
    title: 'Liqui Moly Special 5W-30 (Orange Label) Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '5W-30',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Liqui Moly full synthetic 5W-30 motor oil from the orange-label Special range. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  {
    title: 'Liqui Moly 0W-30 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-30',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Liqui Moly full synthetic 0W-30 passenger car motor oil. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  {
    title: 'Liqui Moly 0W-40 Full Synthetic Motor Oil - 4 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Liqui Moly',
      viscosity: '0W-40',
      'pack-size': '4 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Liqui Moly full synthetic 0W-40 passenger car motor oil. Supplied as a case of four 5 L jugs. Check the label for approvals.',
  },
  {
    title: 'Benzol 0W-20 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '0W-20',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol full synthetic 0W-20 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 5W-20 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '5W-20',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol full synthetic 5W-20 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 5W-30 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '5W-30',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol full synthetic 5W-30 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 5W-40 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '5W-40',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol full synthetic 5W-40 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 5W-40 CK-4 Diesel Engine Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '5W-40 CK-4',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
      specification: ['API CK-4'],
    },
    description: 'Benzol 5W-40 diesel engine oil meeting API CK-4, supplied as a case of four.',
  },
  {
    title: 'Benzol 0W-30 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '0W-30',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol full synthetic 0W-30 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 10W-30 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-semi-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '10W-30',
      'pack-size': 'Case of 4',
    },
    description: 'Benzol 10W-30 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 0W-8 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '0W-8',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol ultra-low-viscosity 0W-8 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 0W-40 Eiffel Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '0W-40',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol Eiffel full synthetic 0W-40 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  {
    title: 'Benzol 0W-16 Klasse 80 Full Synthetic Motor Oil - Case of 4',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Benzol',
      viscosity: '0W-16',
      'pack-size': 'Case of 4',
      'oil-type': 'Full Synthetic',
    },
    description: 'Benzol Klasse 80 full synthetic 0W-16 passenger car motor oil, supplied as a case of four. Check the label for approvals.',
  },
  // source: https://www.castrol.com/en_ca/canada/home/products/our-brands/automotive/castrol-magnatec-engine-oils.html
  {
    title: 'Castrol Magnatec 0W-20 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'dexos1 Gen 3', 'Ford WSS-M2C947-B1', 'Ford WSS-M2C962-A1'],
    },
    description: 'Castrol Magnatec 0W-20 full synthetic passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol Magnatec 5W-20 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'Ford WSS-M2C945-B1', 'Ford WSS-M2C960-A1'],
    },
    description: 'Castrol Magnatec 5W-20 full synthetic passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol Magnatec 5W-30 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'dexos1 Gen 3'],
    },
    description: 'Castrol Magnatec 5W-30 full synthetic passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol Magnatec 0W-16 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-16',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7B'],
    },
    description: 'Castrol Magnatec 0W-16 full synthetic passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  // source: https://www.castrol.com/en_ca/canada/home/products/our-brands/automotive/castrol-edge-oils/castrol-edge.html
  {
    title: 'Castrol EDGE 0W-20 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'dexos1 Gen 3', 'Ford WSS-M2C947-B1', 'Ford WSS-M2C962-A1'],
    },
    description: 'Castrol EDGE 0W-20 full synthetic passenger car motor oil with Fluid Titanium technology, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE 10W-30 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '10W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7'],
    },
    description: 'Castrol EDGE 10W-30 full synthetic passenger car motor oil with Fluid Titanium technology, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE 0W-8 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-8',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Castrol EDGE ultra-low-viscosity 0W-8 full synthetic passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE 5W-30 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'dexos1 Gen 3'],
    },
    description: 'Castrol EDGE 5W-30 full synthetic passenger car motor oil with Fluid Titanium technology, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE 5W-20 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'Ford WSS-M2C945-B1', 'Ford WSS-M2C960-A1'],
    },
    description: 'Castrol EDGE 5W-20 full synthetic passenger car motor oil with Fluid Titanium technology, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE 0W-16 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-16',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['API SP', 'ILSAC GF-7', 'dexos1 Gen 3', 'Ford WSS-M2C947-B1', 'Ford WSS-M2C962-A1'],
    },
    description: 'Castrol EDGE 0W-16 full synthetic passenger car motor oil with Fluid Titanium technology, supplied as a 3-pack of 5 L jugs.',
  },
  // source: https://www.castrol.com/en_ca/canada/home/products/our-brands/automotive/castrol-edge-oils/castrol-edge-euro.html
  {
    title: 'Castrol EDGE Euro 0W-20 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Castrol EDGE Euro 0W-20 advanced full synthetic oil for European vehicles, supplied as a 3-pack of 5 L jugs. Check the label for the specific approvals.',
  },
  {
    title: 'Castrol EDGE Euro 5W-30 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['ACEA A3/B4', 'BMW Longlife-01', 'MB 229.5', 'VW 502 00', 'VW 505 00'],
    },
    description: 'Castrol EDGE Euro 5W-30 advanced full synthetic oil for European vehicles, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE Euro 5W-40 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-40',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['ACEA A3/B4', 'BMW Longlife-01', 'MB 229.5', 'Porsche A40', 'VW 502 00', 'VW 505 00'],
    },
    description: 'Castrol EDGE Euro 5W-40 advanced full synthetic oil for European vehicles, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol EDGE Euro 0W-30 Full Synthetic Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
      specification: ['ACEA A3/B4', 'BMW Longlife-01', 'MB 229.5', 'VW 502 00', 'VW 505 00'],
    },
    description: 'Castrol EDGE Euro 0W-30 advanced full synthetic oil for European vehicles, supplied as a 3-pack of 5 L jugs.',
  },
  // source: https://www.castrol.com/en_ca/canada/home/products/our-brands/automotive/castrol-gtx-oils.html
  {
    title: 'Castrol GTX Full Synthetic 0W-20 Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '0W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Castrol GTX full synthetic 0W-20 passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol GTX Full Synthetic 5W-20 Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-20',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Castrol GTX full synthetic 5W-20 passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Castrol GTX Full Synthetic 5W-30 Motor Oil - 3 x 5 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Castrol',
      viscosity: '5W-30',
      'pack-size': '3 x 5 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Castrol GTX full synthetic 5W-30 passenger car motor oil, supplied as a 3-pack of 5 L jugs.',
  },
  {
    title: 'Mobil 1 0W-20 Full Synthetic Motor Oil - 3 x 4.73 L',
    category: 'pcmo-fully-synthetic',
    attrs: {
      brand: 'Mobil',
      viscosity: '0W-20',
      'pack-size': '3 x 4.73 L',
      'oil-type': 'Full Synthetic',
    },
    description: 'Mobil 1 full synthetic 0W-20 passenger car motor oil, supplied as a 3-pack of 4.73 L jugs.',
  },
]
