import type {ProductInput} from '../types'

export const products: ProductInput[] = [
  {
    title: 'R134a Refrigerant - 12 Pack',
    category: 'refrigerant',
    attrs: {'pack-size': '12 Pack'},
    description: 'R-134a automotive A/C refrigerant sold as a case of 12 cans. Check the label for can size and handling instructions.',
  },
  {
    title: 'R134a Refrigerant - 12 kg Tank',
    category: 'refrigerant',
    attrs: {'pack-size': '12 kg Tank'},
    description: 'R-134a refrigerant supplied in a 12 kg tank for shop use. Check the label for handling and transport requirements.',
  },
  {
    title: 'Emzone R1234yf Refrigerant - 12 Pack',
    category: 'refrigerant',
    attrs: {brand: 'Emzone', 'pack-size': '12 Pack'},
    description: 'Emzone A/C refrigerant for R-1234yf systems, sold as a case of 12. Check the label for can size and handling instructions.',
  },
  {
    title: 'Ultra Cool R12a Refrigerant - 12 Pack',
    category: 'refrigerant',
    attrs: {brand: 'Ultracool', 'pack-size': '12 Pack'},
    description: 'Ultra Cool R12a is a hydrocarbon-based refrigerant that is flammable. Read the label and safety data sheet and confirm local rules before use.',
  },
  {
    title: 'Duracool R1234yf Refrigerant - 12 Pack',
    category: 'refrigerant',
    attrs: {brand: 'Duracool', 'pack-size': '12 Pack'},
    description: 'Duracool A/C refrigerant listed for R-1234yf systems, sold as a case of 12. Check the can label and safety data sheet for refrigerant type and handling.',
  },
  {
    title: 'Duracool 134A/12A Refrigerant - 12 Pack',
    category: 'refrigerant',
    attrs: {brand: 'Duracool', 'pack-size': '12 Pack'},
    description: 'Duracool 12a replacement refrigerant for R-134a systems, listed as 134A/12A NSS. 12a products are hydrocarbon-based; check the label and safety data sheet before use.',
  },
  {
    title: 'Duracool SealQuick A/C Sealant - 12 Pack',
    category: 'ac-sealant-stop-leak',
    attrs: {brand: 'Duracool', 'pack-size': '12 Pack'},
    description: 'Duracool SealQuick is an A/C sealant for R-134a systems that is intended for minor leaks in rubber components. Sold as a case of 12.',
  },
  {
    title: 'Emzone A/C Sealant - 12 Pack',
    category: 'ac-sealant-stop-leak',
    attrs: {brand: 'Emzone', 'pack-size': '12 Pack'},
    description: 'Emzone A/C sealant / stop leak sold as a case of 12. Check the label for compatible refrigerant types.',
  },
  {
    title: 'A/C Gas Hose - R134/12',
    category: 'ac-hoses-adapters',
    description: 'Charging hose for R134/12 A/C systems. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'A/C Gas Hose Adapter',
    category: 'ac-hoses-adapters',
    description: 'Adapter fitting for A/C charging hoses. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'A/C Gas Hose - R1234yf',
    category: 'ac-hoses-adapters',
    description: 'Charging hose for R1234yf A/C systems. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Wurth Gravel Guard Undercoating Spray - 12 Pack',
    category: 'undercoating-rust-protection',
    attrs: {brand: 'Wurth', 'pack-size': '12 Pack'},
    description: 'Wurth gravel guard aerosol undercoating for wheel wells and underbody areas prone to stone chips. Sold as a case of 12.',
  },
  {
    title: 'Undercoating - Amber - Pail',
    category: 'undercoating-rust-protection',
    attrs: {colour: 'Amber', 'pack-size': 'Pail'},
    description: 'Amber undercoating supplied in a pail for brush or spray application. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Undercoating - Black - Pail',
    category: 'undercoating-rust-protection',
    attrs: {colour: 'Black', 'pack-size': 'Pail'},
    description: 'Black undercoating supplied in a pail for brush or spray application. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Rubberized Undercoating - Pail',
    category: 'undercoating-rust-protection',
    attrs: {'pack-size': 'Pail'},
    description: 'Rubberized undercoating supplied in a pail. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Emzone Gravel Guard Undercoating Spray - 12 Pack',
    category: 'undercoating-rust-protection',
    attrs: {brand: 'Emzone', 'pack-size': '12 Pack'},
    description: 'Emzone gravel guard aerosol undercoating sold as a case of 12.',
  },
  {
    title: 'Apel Brake Cleaner - 12 Pack',
    category: 'brake-cleaner',
    attrs: {brand: 'Apel', 'pack-size': '12 Pack'},
    description: 'Apel aerosol brake cleaner sold as a case of 12. Check the label for formula and flammability.',
  },
  {
    title: 'Wurth Brake and Parts Cleaner - 12 Pack',
    category: 'brake-cleaner',
    attrs: {brand: 'Wurth', 'pack-size': '12 Pack'},
    description: 'Wurth aerosol brake and parts cleaner for removing brake dust, dirt and brake fluid. Sold as a case of 12.',
  },
  {
    title: 'Emzone Brake and Parts Cleaner - 12 Pack',
    category: 'brake-cleaner',
    attrs: {brand: 'Emzone', 'pack-size': '12 Pack'},
    description: 'Emzone non-chlorinated aerosol brake and parts cleaner for removing grease, oil and brake fluid. Sold as a case of 12.',
  },
  {
    title: 'Benzol Brake Cleaner - 12 Pack',
    category: 'brake-cleaner',
    attrs: {brand: 'Benzol', 'pack-size': '12 Pack'},
    description: 'Benzol aerosol brake cleaner sold as a case of 12. Check the label for formula and flammability.',
  },
  {
    title: 'Diamond Brake Cleaner - 12 Pack',
    category: 'brake-cleaner',
    attrs: {brand: 'Diamond', 'pack-size': '12 Pack'},
    description: 'Diamond aerosol brake cleaner sold as a case of 12. Check the label for formula and flammability.',
  },
  {
    title: 'Carquest Brake Cleaner - 12 Pack',
    category: 'brake-cleaner',
    attrs: {brand: 'Carquest', 'pack-size': '12 Pack'},
    description: 'Carquest-branded aerosol brake parts cleaner sold as a case of 12. Check the label for formula and flammability.',
  },
  {
    title: 'Kross Brake Cleaner - Pail',
    category: 'brake-cleaner',
    attrs: {brand: 'Kross', 'pack-size': 'Pail'},
    description: 'Kross brake cleaner supplied in a pail for parts-washing use. Check the label for pail size and formula.',
  },
  {
    title: 'Zep Penetrating Spray - 12 Pack',
    category: 'penetrating-spray',
    attrs: {brand: 'Zep', 'pack-size': '12 Pack'},
    description: 'Zep aerosol penetrating lubricant for freeing stuck bolts, nuts and fittings. Sold as a case of 12.',
  },
  {
    title: 'Emzone Penetrating Spray - 12 Pack',
    category: 'penetrating-spray',
    attrs: {brand: 'Emzone', 'pack-size': '12 Pack'},
    description: 'Emzone aerosol penetrating lubricant that loosens and lubricates tight or sticky parts. Sold as a case of 12.',
  },
  {
    title: 'Oil Change Reminder Stickers - 300 Stickers',
    category: 'oil-change-stickers',
    attrs: {'pack-size': '300 Stickers'},
    description: 'Oil change reminder stickers, 300 per pack.',
  },
  {
    title: 'Oil Change Reminder Stickers - 150 Stickers',
    category: 'oil-change-stickers',
    attrs: {'pack-size': '150 Stickers'},
    description: 'Oil change reminder stickers, 150 per pack.',
  },
  {
    title: 'Wiper Blade 12 in',
    category: 'wiper-blades',
    attrs: {size: '12 in'},
    description: 'Windshield wiper blade, 12 inch length.',
  },
  {
    title: 'Wiper Blade 14 in',
    category: 'wiper-blades',
    attrs: {size: '14 in'},
    description: 'Windshield wiper blade, 14 inch length.',
  },
  {
    title: 'Wiper Blade 16 in',
    category: 'wiper-blades',
    attrs: {size: '16 in'},
    description: 'Windshield wiper blade, 16 inch length.',
  },
  {
    title: 'Wiper Blade 17 in',
    category: 'wiper-blades',
    attrs: {size: '17 in'},
    description: 'Windshield wiper blade, 17 inch length.',
  },
  {
    title: 'Wiper Blade 18 in',
    category: 'wiper-blades',
    attrs: {size: '18 in'},
    description: 'Windshield wiper blade, 18 inch length.',
  },
  {
    title: 'Wiper Blade 19 in',
    category: 'wiper-blades',
    attrs: {size: '19 in'},
    description: 'Windshield wiper blade, 19 inch length.',
  },
  {
    title: 'Wiper Blade 20 in',
    category: 'wiper-blades',
    attrs: {size: '20 in'},
    description: 'Windshield wiper blade, 20 inch length.',
  },
  {
    title: 'Wiper Blade 21 in',
    category: 'wiper-blades',
    attrs: {size: '21 in'},
    description: 'Windshield wiper blade, 21 inch length.',
  },
  {
    title: 'Wiper Blade 22 in',
    category: 'wiper-blades',
    attrs: {size: '22 in'},
    description: 'Windshield wiper blade, 22 inch length.',
  },
  {
    title: 'Wiper Blade 24 in',
    category: 'wiper-blades',
    attrs: {size: '24 in'},
    description: 'Windshield wiper blade, 24 inch length.',
  },
  {
    title: 'Wiper Blade 26 in',
    category: 'wiper-blades',
    attrs: {size: '26 in'},
    description: 'Windshield wiper blade, 26 inch length.',
  },
  {
    title: 'Wiper Blade 28 in',
    category: 'wiper-blades',
    attrs: {size: '28 in'},
    description: 'Windshield wiper blade, 28 inch length.',
  },
  {
    title: 'Vent 3 x 10 in - White - 12 Pack',
    category: 'vents-grills',
    attrs: {size: '3 x 10 in', colour: 'White', 'pack-size': '12 Pack'},
    description: 'Vent measuring 3 x 10 inches in white, sold as a pack of 12.',
  },
  {
    title: 'Vent 4 x 10 in - White',
    category: 'vents-grills',
    attrs: {size: '4 x 10 in', colour: 'White'},
    description: 'Vent measuring 4 x 10 inches in white.',
  },
  {
    title: 'Vent 3 x 10 in - Black',
    category: 'vents-grills',
    attrs: {size: '3 x 10 in', colour: 'Black'},
    description: 'Vent measuring 3 x 10 inches in black.',
  },
  {
    title: 'Vent 4 x 10 in - Black',
    category: 'vents-grills',
    attrs: {size: '4 x 10 in', colour: 'Black'},
    description: 'Vent measuring 4 x 10 inches in black.',
  },
  {
    title: 'Shower Heads - Box of 3',
    category: 'other-accessories',
    attrs: {'pack-size': 'Box of 3'},
    description: 'Shower heads, supplied in a box of 3.',
  },
  {
    title: 'Returnable Grills',
    category: 'vents-grills',
    description: 'Returnable grills. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Gloves 6 mil - Small',
    category: 'gloves',
    attrs: {size: 'S'},
    description: 'Disposable gloves, 6 mil thickness, size small.',
  },
  {
    title: 'Gloves 6 mil - Medium',
    category: 'gloves',
    attrs: {size: 'M'},
    description: 'Disposable gloves, 6 mil thickness, size medium.',
  },
  {
    title: 'Gloves 6 mil - Large',
    category: 'gloves',
    attrs: {size: 'L'},
    description: 'Disposable gloves, 6 mil thickness, size large.',
  },
  {
    title: 'Gloves 6 mil - XL',
    category: 'gloves',
    attrs: {size: 'XL'},
    description: 'Disposable gloves, 6 mil thickness, size XL.',
  },
  {
    title: 'Gloves 8 mil - Medium - Purple - Case of 10 Boxes',
    category: 'gloves',
    attrs: {size: 'M', colour: 'Purple', 'pack-size': 'Case of 10 Boxes'},
    description: 'Purple disposable gloves, 8 mil thickness, size medium. Case of 10 boxes with 100 gloves per box.',
  },
  {
    title: 'Gloves 8 mil - Large - Blue - Box of 50',
    category: 'gloves',
    attrs: {size: 'L', colour: 'Blue', 'pack-size': 'Box of 50'},
    description: 'Blue disposable gloves, 8 mil thickness, size large. 50 gloves per box.',
  },
  {
    title: 'Grizzly Gloves 8 mil - Large - Orange',
    category: 'gloves',
    attrs: {brand: 'Grizzly', size: 'L', colour: 'Orange'},
    description: 'Grizzly orange disposable gloves, 8 mil thickness, size large.',
  },
  {
    title: 'Grizzly Gloves 8 mil - XL',
    category: 'gloves',
    attrs: {brand: 'Grizzly', size: 'XL'},
    description: 'Grizzly disposable gloves, 8 mil thickness, size XL.',
  },
  {
    title: 'Azguard Gloves 6 mil - Large',
    category: 'gloves',
    attrs: {brand: 'Azguard', size: 'L'},
    description: 'Azguard disposable gloves, 6 mil thickness, size large.',
  },
  {
    title: 'Azguard Gloves 8 mil - XL',
    category: 'gloves',
    attrs: {brand: 'Azguard', size: 'XL'},
    description: 'Azguard disposable gloves, 8 mil thickness, size XL.',
  },
  {
    title: 'Azguard Gloves 10 mil - XL',
    category: 'gloves',
    attrs: {brand: 'Azguard', size: 'XL'},
    description: 'Azguard disposable gloves, 10 mil thickness, size XL.',
  },
  {
    title: 'Tire and Tube Mounting Compound',
    category: 'shop-chemicals',
    description: 'Mounting compound (tire lubricant) for seating tires and tubes on rims. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Dash Spray',
    category: 'shop-chemicals',
    description: 'Dash spray for cleaning and dressing interior dashboard surfaces. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Tire Shine Spray',
    category: 'shop-chemicals',
    description: 'Spray-on tire shine for dressing tire sidewalls. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Kross Rust Remover',
    category: 'shop-chemicals',
    attrs: {brand: 'Kross'},
    description: 'Kross rust remover. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Rags',
    category: 'rags-wipes-paper',
    description: 'Shop rags for general cleaning and wiping. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Letter Size Paper - Pack of 10',
    category: 'rags-wipes-paper',
    attrs: {size: 'Letter', 'pack-size': 'Pack of 10'},
    description: 'Letter-size paper, 8.5 x 11 inches. Pack of 10 reams with 500 sheets each.',
  },
  {
    title: 'Cleaning Wipes - 12 Pack',
    category: 'rags-wipes-paper',
    attrs: {'pack-size': '12 Pack'},
    description: 'Cleaning wipes sold as a pack of 12. Generic listing; check the product label and safety data sheet for full details.',
  },
  {
    title: 'Grime Eater Hand Soap',
    category: 'hand-soap',
    attrs: {brand: 'Grime Eater'},
    description: 'Grime Eater hand soap for shop use. Check the label for formula and size.',
  },
  {
    title: 'Hand Soap Regular - 4 x 4 L',
    category: 'hand-soap',
    attrs: {'pack-size': '4 x 4 L'},
    description: 'Regular hand soap in a case of four 4 L jugs.',
  },
  {
    title: 'Strong Clear Garbage Bags 42 x 48 in - 100 Pack',
    category: 'garbage-bags',
    attrs: {size: '42 x 48 in', colour: 'Clear', 'pack-size': '100 Pack'},
    description: 'Strong clear garbage bags, 42 x 48 inches, 100 bags per pack.',
  },
  {
    title: 'Strong Black Garbage Bags 42 x 48 in - 100 Pack',
    category: 'garbage-bags',
    attrs: {size: '42 x 48 in', colour: 'Black', 'pack-size': '100 Pack'},
    description: 'Strong black garbage bags, 42 x 48 inches, 100 bags per pack.',
  },
  {
    title: 'Clip-On Wheel Weights 0.25 oz - Box of 50',
    category: 'wheel-weights',
    attrs: {size: '0.25 oz', 'pack-size': 'Box of 50'},
    description: 'Clip-on wheel balancing weights, 0.25 oz each, 50 per box.',
  },
  {
    title: 'Clip-On Wheel Weights 0.50 oz - Box of 50',
    category: 'wheel-weights',
    attrs: {size: '0.50 oz', 'pack-size': 'Box of 50'},
    description: 'Clip-on wheel balancing weights, 0.50 oz each, 50 per box.',
  },
  {
    title: 'Clip-On Wheel Weights 1.00 oz - Box of 50',
    category: 'wheel-weights',
    attrs: {size: '1.00 oz', 'pack-size': 'Box of 50'},
    description: 'Clip-on wheel balancing weights, 1.00 oz each, 50 per box.',
  },
  {
    title: 'Adhesive Wheel Balance Weights 0.25 oz - 4 Pack',
    category: 'wheel-weights',
    attrs: {size: '0.25 oz', 'pack-size': '4 Pack'},
    description: 'Adhesive wheel balancing weights, 0.25 oz, pack of 4.',
  },
  {
    title: 'Adhesive Wheel Balance Weights 0.50 oz - 4 Pack',
    category: 'wheel-weights',
    attrs: {size: '0.50 oz', 'pack-size': '4 Pack'},
    description: 'Adhesive wheel balancing weights, 0.50 oz, pack of 4.',
  },
  {
    title: 'Ceratec Wheel Balancing - Box of 6',
    category: 'wheel-weights',
    attrs: {brand: 'Ceratec', 'pack-size': 'Box of 6'},
    description: 'Ceratec wheel balancing product, box of 6. Generic listing; check the product label and safety data sheet for full details.',
  },
]
