import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Standalone Sanity Studio has its own toolchain.
    "studio/**",
    // Generated by Sanity TypeGen / drizzle-kit.
    "src/sanity/types.ts",
    "drizzle/**",
  ]),
]);

export default eslintConfig;
