/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AttributeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "attribute";
};

export type AttributeValue = {
  _id: string;
  _type: "attributeValue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  attribute: AttributeReference;
  label: string;
  slug: Slug;
  sortOrder?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Attribute = {
  _id: string;
  _type: "attribute";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  vertical: "automotive" | "baby" | "home";
  filterable?: boolean;
  allowMultiple?: boolean;
  sortOrder?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AttributeValueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "attributeValue";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  vertical: "automotive" | "baby" | "home";
  sku?: string;
  inStock: boolean;
  category: CategoryReference;
  attributeValues?: Array<
    {
      _key: string;
    } & AttributeValueReference
  >;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  vertical: "automotive" | "baby" | "home";
  level: 1 | 2 | 3;
  parent?: CategoryReference;
  sortOrder?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AttributeReference
  | AttributeValue
  | Slug
  | Attribute
  | CategoryReference
  | AttributeValueReference
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/features/catalog/queries.ts
// Variable: CATEGORY_TREE_QUERY
// Query: *[_type == "category" && vertical == "automotive" && level == 1] | order(sortOrder asc, title asc) {    _id,    title,    "slug": slug.current,    "children": *[_type == "category" && vertical == "automotive" && parent._ref == ^._id] | order(sortOrder asc, title asc) {      _id,      title,      "slug": slug.current,      "children": *[_type == "category" && vertical == "automotive" && parent._ref == ^._id] | order(sortOrder asc, title asc) {        _id,        title,        "slug": slug.current      }    }  }
export type CATEGORY_TREE_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  children: Array<{
    _id: string;
    title: string;
    slug: string;
    children: Array<{
      _id: string;
      title: string;
      slug: string;
    }>;
  }>;
}>;

// Source: ../src/features/catalog/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && vertical == "automotive" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    level,    "ancestors": [      parent->parent->{ title, "slug": slug.current },      parent->{ title, "slug": slug.current }    ][defined(slug)],    "children": *[_type == "category" && vertical == "automotive" && parent._ref == ^._id] | order(sortOrder asc, title asc) {      _id,      title,      "slug": slug.current    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  level: 1 | 2 | 3;
  ancestors: Array<{
    title: string;
    slug: string;
  } | null>;
  children: Array<{
    _id: string;
    title: string;
    slug: string;
  }>;
} | null;

// Source: ../src/features/catalog/queries.ts
// Variable: PRODUCT_LIST_QUERY
// Query: *[  _type == "product" && vertical == "automotive"  && (!defined($q) || title match $q || sku match $q)  && (!defined($category) || $category in [    category->slug.current,    category->parent->slug.current,    category->parent->parent->slug.current  ])  && (!$available || inStock == true)] | order(title asc) {  _id,  title,  "slug": slug.current,  sku,  inStock,  "image": images[0],  "category": category->{ title, "slug": slug.current },  "attributeLabels": attributeValues[]->label}
export type PRODUCT_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  sku: string | null;
  inStock: boolean;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
  category: {
    title: string;
    slug: string;
  };
  attributeLabels: Array<string> | null;
}>;

// Source: ../src/features/catalog/queries.ts
// Variable: FACETS_QUERY
// Query: *[_type == "attribute" && vertical == "automotive" && filterable == true] | order(sortOrder asc, title asc) {    _id,    title,    "key": slug.current,    "values": *[_type == "attributeValue" && attribute._ref == ^._id] | order(sortOrder asc, label asc) {      _id,      label,      "key": slug.current,      "count": count(*[  _type == "product" && vertical == "automotive"  && (!defined($q) || title match $q || sku match $q)  && (!defined($category) || $category in [    category->slug.current,    category->parent->slug.current,    category->parent->parent->slug.current  ])  && (!$available || inStock == true) && references(^._id)])    }[count > 0]  }[count(values) > 0]
export type FACETS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  key: string;
  values: Array<{
    _id: string;
    label: string;
    key: string;
    count: number;
  }>;
}>;

// Source: ../src/features/catalog/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && vertical == "automotive" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    sku,    inStock,    images,    description,    "categoryPath": [  category->parent->parent->{ title, "slug": slug.current },  category->parent->{ title, "slug": slug.current },  category->{ title, "slug": slug.current }][defined(slug)],    "attributeValues": attributeValues[]->{  label,  sortOrder,  "attribute": attribute->{ _id, title, sortOrder }}  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  sku: string | null;
  inStock: boolean;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  categoryPath: Array<{
    title: string;
    slug: string;
  } | null>;
  attributeValues: Array<{
    label: string;
    sortOrder: number | null;
    attribute: {
      _id: string;
      title: string;
      sortOrder: number | null;
    };
  }> | null;
} | null;

// Source: ../src/features/catalog/queries.ts
// Variable: PRODUCT_AVAILABILITY_QUERY
// Query: *[_type == "product" && vertical == "automotive" && _id in $ids] { _id, inStock }
export type PRODUCT_AVAILABILITY_QUERY_RESULT = Array<{
  _id: string;
  inStock: boolean;
}>;

// Source: ../src/features/catalog/queries.ts
// Variable: QUOTE_PRODUCTS_QUERY
// Query: *[_type == "product" && vertical == "automotive" && _id in $ids] {    _id,    title,    sku,    inStock,    "categoryPath": [  category->parent->parent->{ title, "slug": slug.current },  category->parent->{ title, "slug": slug.current },  category->{ title, "slug": slug.current }][defined(slug)],    "attributeValues": attributeValues[]->{  label,  sortOrder,  "attribute": attribute->{ _id, title, sortOrder }}  }
export type QUOTE_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  sku: string | null;
  inStock: boolean;
  categoryPath: Array<{
    title: string;
    slug: string;
  } | null>;
  attributeValues: Array<{
    label: string;
    sortOrder: number | null;
    attribute: {
      _id: string;
      title: string;
      sortOrder: number | null;
    };
  }> | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "category" && vertical == "automotive" && level == 1] | order(sortOrder asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "children": *[_type == "category" && vertical == "automotive" && parent._ref == ^._id] | order(sortOrder asc, title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      "children": *[_type == "category" && vertical == "automotive" && parent._ref == ^._id] | order(sortOrder asc, title asc) {\n        _id,\n        title,\n        "slug": slug.current\n      }\n    }\n  }\n': CATEGORY_TREE_QUERY_RESULT;
    '\n  *[_type == "category" && vertical == "automotive" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    level,\n    "ancestors": [\n      parent->parent->{ title, "slug": slug.current },\n      parent->{ title, "slug": slug.current }\n    ][defined(slug)],\n    "children": *[_type == "category" && vertical == "automotive" && parent._ref == ^._id] | order(sortOrder asc, title asc) {\n      _id,\n      title,\n      "slug": slug.current\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[\n  _type == "product" && vertical == "automotive"\n  && (!defined($q) || title match $q || sku match $q)\n  && (!defined($category) || $category in [\n    category->slug.current,\n    category->parent->slug.current,\n    category->parent->parent->slug.current\n  ])\n  && (!$available || inStock == true)\n] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  sku,\n  inStock,\n  "image": images[0],\n  "category": category->{ title, "slug": slug.current },\n  "attributeLabels": attributeValues[]->label\n}': PRODUCT_LIST_QUERY_RESULT;
    '\n  *[_type == "attribute" && vertical == "automotive" && filterable == true] | order(sortOrder asc, title asc) {\n    _id,\n    title,\n    "key": slug.current,\n    "values": *[_type == "attributeValue" && attribute._ref == ^._id] | order(sortOrder asc, label asc) {\n      _id,\n      label,\n      "key": slug.current,\n      "count": count(*[\n  _type == "product" && vertical == "automotive"\n  && (!defined($q) || title match $q || sku match $q)\n  && (!defined($category) || $category in [\n    category->slug.current,\n    category->parent->slug.current,\n    category->parent->parent->slug.current\n  ])\n  && (!$available || inStock == true)\n && references(^._id)])\n    }[count > 0]\n  }[count(values) > 0]\n': FACETS_QUERY_RESULT;
    '\n  *[_type == "product" && vertical == "automotive" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    sku,\n    inStock,\n    images,\n    description,\n    "categoryPath": [\n  category->parent->parent->{ title, "slug": slug.current },\n  category->parent->{ title, "slug": slug.current },\n  category->{ title, "slug": slug.current }\n][defined(slug)],\n    "attributeValues": attributeValues[]->{\n  label,\n  sortOrder,\n  "attribute": attribute->{ _id, title, sortOrder }\n}\n  }\n': PRODUCT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "product" && vertical == "automotive" && _id in $ids] { _id, inStock }\n': PRODUCT_AVAILABILITY_QUERY_RESULT;
    '\n  *[_type == "product" && vertical == "automotive" && _id in $ids] {\n    _id,\n    title,\n    sku,\n    inStock,\n    "categoryPath": [\n  category->parent->parent->{ title, "slug": slug.current },\n  category->parent->{ title, "slug": slug.current },\n  category->{ title, "slug": slug.current }\n][defined(slug)],\n    "attributeValues": attributeValues[]->{\n  label,\n  sortOrder,\n  "attribute": attribute->{ _id, title, sortOrder }\n}\n  }\n': QUOTE_PRODUCTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
